import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { generateAll, parseOpenApi } from '../../../src/core'
import { run } from './index'

const roots: string[] = []
const spec = `openapi: 3.1.0
info: { title: CLI, version: 1.0.0 }
paths:
  /users:
    get:
      operationId: getUsers
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items: { type: string }
`

async function workspace() {
  const root = await mkdtemp(join(tmpdir(), 'api-bridge-cli-'))
  roots.push(root)
  const input = join(root, 'openapi.yaml')
  await writeFile(input, spec)
  return { root, input, output: join(root, 'generated') }
}

afterEach(async () => {
  vi.restoreAllMocks()
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })))
})

describe('CLI', () => {
  it('checks, generates deterministically and detects stale files without changing them', async () => {
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    const { input, output } = await workspace()
    expect(await run(['check', input, '--json'])).toBe(0)
    expect(
      await run(['generate', input, '--output', output, '--targets', 'typescript,fetch']),
    ).toBe(0)
    await writeFile(join(output, 'user-file.ts'), 'keep me')
    expect(await run(['generate', input, '--output', output, '--check'])).toBe(2)
    expect(await readFile(join(output, 'user-file.ts'), 'utf8')).toBe('keep me')
    const before = await readFile(join(output, 'api-types.ts'), 'utf8')
    expect(before).toContain('Do not edit')
    const parsed = parseOpenApi(spec)
    const coreTypes = generateAll(parsed.document, parsed.operations).find(
      (file) => file.name === 'api-types.ts',
    )!.content
    expect(
      before.replace(/^\/\* Generated by API Bridge.+\*\/\n/, '/* Generated by API Bridge. */\n'),
    ).toBe(coreTypes)
    expect(
      await run(['generate', input, '--output', output, '--targets', 'typescript,fetch']),
    ).toBe(0)
    expect(
      await run([
        'generate',
        input,
        '--output',
        output,
        '--targets',
        'typescript,fetch',
        '--check',
      ]),
    ).toBe(0)
  })

  it('diff exits 2 for breaking changes and validate-response is machine readable', async () => {
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    const { root, input } = await workspace()
    const candidate = join(root, 'candidate.yaml')
    const response = join(root, 'response.json')
    await writeFile(candidate, spec.replace('/users:', '/people:'))
    await writeFile(response, '["Ada"]')
    expect(await run(['diff', input, candidate, '--format', 'json'])).toBe(2)
    expect(
      await run([
        'validate-response',
        input,
        '--operation',
        'getUsers',
        '--status',
        '200',
        '--input',
        response,
        '--json',
      ]),
    ).toBe(0)
  })

  it('loads a TypeScript config while CLI flags take precedence', async () => {
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    const { root, input, output } = await workspace()
    const config = join(root, 'api-bridge.config.ts')
    await writeFile(
      config,
      `export default { input: ${JSON.stringify(input)}, output: ${JSON.stringify(output)}, targets: ['zod'] }`,
    )
    expect(await run(['generate', '--config', config, '--targets', 'typescript'])).toBe(0)
    expect(await readFile(join(output, 'api-types.ts'), 'utf8')).toContain('Generated by')
    await expect(readFile(join(output, 'api-schemas.ts'), 'utf8')).rejects.toThrow()
  })

  it('rejects an unknown manifest major instead of guessing compatibility', async () => {
    vi.spyOn(process.stdout, 'write').mockImplementation(() => true)
    vi.spyOn(process.stderr, 'write').mockImplementation(() => true)
    const { input, output } = await workspace()
    expect(await run(['generate', input, '--output', output])).toBe(0)
    const path = join(output, '.api-bridge-manifest.json')
    const manifest = JSON.parse(await readFile(path, 'utf8')) as { schemaVersion: string }
    manifest.schemaVersion = '2.0.0'
    await writeFile(path, JSON.stringify(manifest))
    expect(await run(['generate', input, '--output', output, '--check'])).toBe(1)
  })

  it('rejects an unknown config major', async () => {
    vi.spyOn(process.stderr, 'write').mockImplementation(() => true)
    const { root } = await workspace()
    const config = join(root, 'api-bridge.config.ts')
    await writeFile(config, `export default { schemaVersion: '2.0.0' }`)
    expect(await run(['generate', '--config', config])).toBe(1)
  })

  it('leaves the previous target untouched when writing cannot start', async () => {
    vi.spyOn(process.stderr, 'write').mockImplementation(() => true)
    const { root, input } = await workspace()
    const blocked = join(root, 'blocked-output')
    await writeFile(blocked, 'not a directory')
    expect(await run(['generate', input, '--output', blocked])).toBe(1)
    expect(await readFile(blocked, 'utf8')).toBe('not a directory')
  })
})
