import { createHash } from 'node:crypto'
import { cp, mkdir, mkdtemp, readFile, rename, rm, stat, writeFile } from 'node:fs/promises'
import { basename, dirname, join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { createJiti } from 'jiti'
import {
  CORE_API_VERSION,
  DIFF_REPORT_SCHEMA_VERSION,
  MANIFEST_SCHEMA_VERSION,
  assertCompatibleMajor,
  diffOpenApi,
  diffToMarkdown,
  generateAll,
  parseOpenApi,
  validateValue,
  type GeneratedFile,
} from '../../../src/core/index'

const TOOL_VERSION = '0.1.0'
export const CONFIG_SCHEMA_VERSION = '1.0.0' as const
const MANIFEST = '.api-bridge-manifest.json'
const TARGET_FILES = {
  typescript: 'api-types.ts',
  zod: 'api-schemas.ts',
  msw: 'api-handlers.ts',
  fetch: 'api-fetch.ts',
  axios: 'api-axios.ts',
  query: 'api-query-options.ts',
} as const
type Target = keyof typeof TARGET_FILES
export type ApiBridgeConfig = {
  schemaVersion?: typeof CONFIG_SCHEMA_VERSION
  input?: string
  output?: string
  targets?: Target[]
}
export type ApiBridgeManifest = {
  schemaVersion: typeof MANIFEST_SCHEMA_VERSION
  toolVersion: string
  coreApiVersion: string
  input: { filename: string; sha256: string }
  config: { targets: Target[] }
  managedFiles: string[]
}

const help = `API Bridge ${TOOL_VERSION}

Usage:
  api-bridge generate <openapi> --output <dir> [--targets typescript,zod,msw,fetch,axios,query] [--dry-run|--check]
  api-bridge diff <baseline> <candidate> [--format markdown|json] [--output <file>]
  api-bridge validate-response <openapi> --operation <id> --status <code> --input <response.json>
  api-bridge check <openapi>

Global options: --config <api-bridge.config.ts> --json --help --version`

function parseArgs(argv: string[]) {
  const positionals: string[] = []
  const flags = new Map<string, string | true>()
  for (let index = 0; index < argv.length; index++) {
    const value = argv[index]
    if (!value.startsWith('--')) positionals.push(value)
    else if (['--json', '--dry-run', '--check', '--help', '--version'].includes(value))
      flags.set(value.slice(2), true)
    else {
      const next = argv[++index]
      if (!next || next.startsWith('--')) throw new Error(`${value} requires a value.`)
      flags.set(value.slice(2), next)
    }
  }
  return { positionals, flags }
}

async function exists(path: string) {
  try {
    await stat(path)
    return true
  } catch {
    return false
  }
}

async function loadConfig(path: string | undefined): Promise<ApiBridgeConfig> {
  const candidate = resolve(path ?? 'api-bridge.config.ts')
  if (!path && !(await exists(candidate))) return {}
  if (!(await exists(candidate))) throw new Error(`Config file not found: ${candidate}`)
  const jiti = createJiti(import.meta.url, { interopDefault: true })
  const loaded = (await jiti.import(candidate, { default: true })) as ApiBridgeConfig
  if (loaded?.schemaVersion) assertCompatibleMajor(loaded.schemaVersion)
  return loaded ?? {}
}

async function loadSpec(path: string) {
  const absolute = resolve(path)
  let source: string
  try {
    source = await readFile(absolute, 'utf8')
  } catch (error) {
    throw new Error(`Cannot read OpenAPI file ${absolute}: ${String(error)}`)
  }
  return { absolute, source, parsed: parseOpenApi(source, basename(absolute)) }
}

const hash = (value: string) => createHash('sha256').update(value).digest('hex')
const stableJson = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`

function selectedTargets(value: string | undefined, config: ApiBridgeConfig): Target[] {
  const requested = value ? value.split(',') : (config.targets ?? Object.keys(TARGET_FILES))
  const targets = [...new Set(requested)].sort() as Target[]
  for (const target of targets)
    if (!(target in TARGET_FILES)) throw new Error(`Unknown generation target: ${target}`)
  return targets
}

function generatedFiles(
  source: string,
  inputName: string,
  config: ApiBridgeConfig,
  targetFlag?: string,
) {
  const parsed = parseOpenApi(source, inputName)
  const targets = selectedTargets(targetFlag, config)
  const names = new Set<string>(targets.map((target) => TARGET_FILES[target]))
  const header = `/* Generated by API Bridge ${TOOL_VERSION} from ${basename(inputName)}. Do not edit. */\n`
  const files = generateAll(parsed.document, parsed.operations)
    .filter((file) => names.has(file.name))
    .map((file) => ({
      ...file,
      content: `${header}${file.content.replace(/^\/\* Generated by API Bridge\. \*\/\n?/, '')}`,
    }))
  return { files, targets }
}

async function readManifest(output: string): Promise<ApiBridgeManifest | undefined> {
  try {
    const manifest = JSON.parse(await readFile(join(output, MANIFEST), 'utf8')) as ApiBridgeManifest
    assertCompatibleMajor(manifest.schemaVersion)
    if (
      !Array.isArray(manifest.managedFiles) ||
      manifest.managedFiles.some((name) => basename(name) !== name)
    )
      throw new Error(`Invalid managed file list in ${join(output, MANIFEST)}.`)
    return manifest
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw error
  }
}

async function mismatches(output: string, files: GeneratedFile[], manifest: ApiBridgeManifest) {
  const expected = [...files.map((file) => file.name), MANIFEST].sort()
  const differences: string[] = []
  for (const file of files) {
    try {
      if ((await readFile(join(output, file.name), 'utf8')) !== file.content)
        differences.push(file.name)
    } catch {
      differences.push(file.name)
    }
  }
  try {
    if ((await readFile(join(output, MANIFEST), 'utf8')) !== stableJson(manifest))
      differences.push(MANIFEST)
  } catch {
    differences.push(MANIFEST)
  }
  const previous = await readManifest(output)
  for (const name of previous?.managedFiles ?? [])
    if (!expected.includes(name)) differences.push(name)
  return [...new Set(differences)].sort()
}

async function atomicWrite(output: string, files: GeneratedFile[], manifest: ApiBridgeManifest) {
  const absolute = resolve(output)
  const parent = dirname(absolute)
  await mkdir(parent, { recursive: true })
  const stagingRoot = await mkdtemp(join(parent, `.${basename(absolute)}-staging-`))
  const staged = join(stagingRoot, basename(absolute))
  const backup = join(stagingRoot, `${basename(absolute)}-backup`)
  const hadOutput = await exists(absolute)
  try {
    if (hadOutput) await cp(absolute, staged, { recursive: true })
    else await mkdir(staged, { recursive: true })
    const previous = await readManifest(absolute)
    for (const name of previous?.managedFiles ?? []) await rm(join(staged, name), { force: true })
    await Promise.all(files.map((file) => writeFile(join(staged, file.name), file.content, 'utf8')))
    await writeFile(join(staged, MANIFEST), stableJson(manifest), 'utf8')
    if (hadOutput) await rename(absolute, backup)
    try {
      await rename(staged, absolute)
    } catch (error) {
      if (hadOutput) await rename(backup, absolute)
      throw error
    }
  } finally {
    await rm(stagingRoot, { recursive: true, force: true })
  }
}

function output(json: boolean, payload: Record<string, unknown>, message: string) {
  process.stdout.write(json ? stableJson(payload) : `${message}\n`)
}

const diffReasons: Record<string, string> = {
  'endpoint-removed': 'Removing an endpoint breaks existing calls.',
  'endpoint-added': 'Adding an endpoint is backward compatible.',
  'parameter-removed': 'Removing an existing request parameter breaks callers.',
  'parameter-added': 'Review whether the new request parameter is required.',
  'parameter-required': 'Making a request parameter required breaks existing calls.',
  'request-body-removed': 'Removing the request body changes the call contract.',
  'request-body-added': 'Review whether the new request body is required.',
  'request-body-required': 'Making the request body required breaks existing calls.',
  'request-content-type-changed': 'Changing request content type breaks serialization.',
  'response-removed': 'Removing a declared response breaks consumers of that branch.',
  'response-added': 'A new response status requires consumer review.',
  'schema-type-changed': 'A response type change invalidates consumer assumptions.',
  'nullable-changed': 'Nullable behavior changed and requires consumer review.',
  'ref-changed': 'The referenced component changed and requires structural review.',
  'enum-shrunk': 'The response enum narrowed; review behavior changes.',
  'enum-expanded': 'The response may contain a new enum value.',
  'response-field-removed': 'Removing a response field breaks consumers.',
  'response-field-added': 'Adding a response field is normally compatible.',
  'required-added': 'A response field became required; review historical data.',
  'required-removed': 'A previously required response field may now be absent.',
  'component-removed': 'Removing a component schema breaks references.',
  'component-added': 'Adding a component schema is backward compatible.',
}

function englishParseMessage(message: string) {
  return message
    .replace('文件超过 10 MiB 导入限制。', 'The file exceeds the 10 MiB import limit.')
    .replace('文档根节点必须是对象。', 'The document root must be an object.')
    .replace(
      '仅支持 OpenAPI 3.0 和 3.1 文档。',
      'Only OpenAPI 3.0 and 3.1 documents are supported.',
    )
    .replace(/^语法错误：/, 'Syntax error: ')
    .replace(/^外部 \$ref 暂不解析：/, 'External $ref is not resolved: ')
    .replace(/^无法解析 \$ref：/, 'Cannot resolve $ref: ')
    .replace(/^operationId 冲突：/, 'Duplicate operationId: ')
    .replace('缺少必需的 info 对象。', 'The required info object is missing.')
    .replace('缺少必需的 paths 对象。', 'The required paths object is missing.')
    .replace('文档中没有 endpoint。', 'The document contains no endpoints.')
}

async function generate(args: ReturnType<typeof parseArgs>, config: ApiBridgeConfig) {
  const input = args.positionals[1] ?? config.input
  const outputDir = String(args.flags.get('output') ?? config.output ?? '')
  if (!input || !outputDir) throw new Error('generate requires an input and --output directory.')
  const spec = await loadSpec(input)
  const { files, targets } = generatedFiles(
    spec.source,
    spec.absolute,
    config,
    args.flags.get('targets') as string | undefined,
  )
  const manifest: ApiBridgeManifest = {
    schemaVersion: MANIFEST_SCHEMA_VERSION,
    toolVersion: TOOL_VERSION,
    coreApiVersion: CORE_API_VERSION,
    input: { filename: basename(spec.absolute), sha256: hash(spec.source) },
    config: { targets },
    managedFiles: [...files.map((file) => file.name), MANIFEST].sort(),
  }
  const changed = await mismatches(resolve(outputDir), files, manifest)
  const json = args.flags.has('json')
  if (args.flags.has('check')) {
    output(
      json,
      { ok: !changed.length, changed },
      changed.length ? `Out of date: ${changed.join(', ')}` : 'Generated files are up to date.',
    )
    return changed.length ? 2 : 0
  }
  if (args.flags.has('dry-run')) {
    output(
      json,
      { ok: true, dryRun: true, files: files.map((file) => file.name), changed },
      `Would write ${files.length} files to ${resolve(outputDir)}.`,
    )
    return 0
  }
  await atomicWrite(outputDir, files, manifest)
  output(
    json,
    { ok: true, files: files.map((file) => file.name) },
    `Generated ${files.length} files in ${resolve(outputDir)}.`,
  )
  return 0
}

async function diff(args: ReturnType<typeof parseArgs>) {
  const [baseline, candidate] = args.positionals.slice(1)
  if (!baseline || !candidate) throw new Error('diff requires baseline and candidate files.')
  const before = await loadSpec(baseline)
  const after = await loadSpec(candidate)
  const items = diffOpenApi(
    before.parsed.document,
    before.parsed.operations,
    after.parsed.document,
    after.parsed.operations,
  ).map((item) => ({ ...item, reason: diffReasons[item.kind] ?? 'Review this change.' }))
  const format = String(args.flags.get('format') ?? (args.flags.has('json') ? 'json' : 'markdown'))
  if (!['markdown', 'json'].includes(format)) throw new Error('--format must be markdown or json.')
  const report =
    format === 'json'
      ? stableJson({ schemaVersion: DIFF_REPORT_SCHEMA_VERSION, items })
      : diffToMarkdown(items)
  const destination = args.flags.get('output')
  if (typeof destination === 'string') await writeFile(resolve(destination), report, 'utf8')
  else process.stdout.write(report)
  return items.some((item) => item.severity === 'breaking') ? 2 : 0
}

async function validateResponse(args: ReturnType<typeof parseArgs>) {
  const specPath = args.positionals[1]
  const inputPath = args.flags.get('input')
  const operationId = args.flags.get('operation')
  const status = String(args.flags.get('status') ?? '')
  if (!specPath || typeof inputPath !== 'string' || typeof operationId !== 'string' || !status)
    throw new Error('validate-response requires a spec, --operation, --status and --input.')
  const spec = await loadSpec(specPath)
  const operation = spec.parsed.operations.find(
    (item) => item.operationId === operationId || item.id === operationId,
  )
  if (!operation)
    throw new Error(`Operation not found: ${operationId}. Check operationId in the spec.`)
  const response = operation.responses.find((item) => item.status === status)
  if (!response) throw new Error(`Response ${status} is not declared for ${operationId}.`)
  let value: unknown
  try {
    value = response.contentType.includes('json')
      ? JSON.parse(await readFile(resolve(inputPath), 'utf8'))
      : await readFile(resolve(inputPath), 'utf8')
  } catch {
    throw new Error(`Cannot parse response input ${resolve(inputPath)}. Provide valid JSON/text.`)
  }
  const issues = validateValue(value, response.schema, spec.parsed.document).map((issue) => ({
    ...issue,
    message: `Value at ${issue.pointer} does not match the declared schema.`,
    suggestion: `Expected ${issue.expected}; provide a compatible value.`,
  }))
  output(
    args.flags.has('json'),
    { ok: !issues.length, issues },
    issues.length
      ? `${issues.length} validation issue(s).`
      : 'Response matches the declared schema.',
  )
  return issues.length ? 2 : 0
}

async function check(args: ReturnType<typeof parseArgs>) {
  const input = args.positionals[1]
  if (!input) throw new Error('check requires an OpenAPI file.')
  const spec = await loadSpec(input)
  const issues = spec.parsed.issues.map((issue) => ({
    ...issue,
    message: englishParseMessage(issue.message),
    suggestion:
      issue.code === 'external-ref'
        ? 'Bundle the referenced schema into the local document.'
        : issue.code === 'unresolved-ref'
          ? 'Correct the local JSON Pointer or add the referenced component.'
          : issue.code === 'duplicate-operation-id'
            ? 'Assign a unique operationId to every operation.'
            : issue.code === 'missing-info' || issue.code === 'missing-paths'
              ? `Add the required ${issue.code === 'missing-info' ? 'info' : 'paths'} object.`
              : 'Review the OpenAPI location and update the document.',
  }))
  const errors = issues.filter((issue) => issue.severity === 'error')
  output(
    args.flags.has('json'),
    { ok: !errors.length, issues },
    errors.length
      ? `${errors.length} OpenAPI error(s).`
      : `OpenAPI valid: ${spec.parsed.operations.length} operation(s).`,
  )
  return errors.length ? 2 : 0
}

export async function run(argv = process.argv.slice(2)) {
  try {
    const args = parseArgs(argv)
    if (args.flags.has('version')) {
      process.stdout.write(`${TOOL_VERSION}\n`)
      return 0
    }
    if (args.flags.has('help') || !args.positionals.length) {
      process.stdout.write(`${help}\n`)
      return 0
    }
    const config = await loadConfig(args.flags.get('config') as string | undefined)
    const command = args.positionals[0]
    if (command === 'generate') return await generate(args, config)
    if (command === 'diff') return await diff(args)
    if (command === 'validate-response') return await validateResponse(args)
    if (command === 'check') return await check(args)
    throw new Error(`Unknown command: ${command}. Run api-bridge --help.`)
  } catch (error) {
    const message = englishParseMessage(error instanceof Error ? error.message : String(error))
    if (argv.includes('--json')) process.stderr.write(stableJson({ ok: false, error: message }))
    else process.stderr.write(`Error: ${message}\n`)
    return 1
  }
}

const invoked = process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url
if (invoked) process.exitCode = await run()

export const __testing = { atomicWrite, generatedFiles, parseArgs }
