import type { GeneratedFile, Operation } from './types'

const safeName = (value: string) =>
  value
    .replace(/[^a-zA-Z0-9_$]+(.)?/g, (_, next: string) => (next ? next.toUpperCase() : ''))
    .replace(/^[^a-zA-Z_$]/, '_$&') || 'operation'
const operationName = (operation: Operation) => safeName(operation.operationId ?? operation.id)
const pathExpression = (path: string) =>
  `\`${path.replace(/{([^}]+)}/g, '${encodeURIComponent(String(params.path?.["$1"]))}')}\``

const shared = `export type ApiError = { status: number; body: unknown }\nexport type RequestParams = { path?: Record<string, string | number>; query?: Record<string, string | number | boolean | null | undefined>; headers?: Record<string, string>; body?: unknown; signal?: AbortSignal }\nconst queryString = (query: RequestParams['query']) => { const value = new URLSearchParams(); Object.entries(query ?? {}).sort(([a],[b]) => a.localeCompare(b)).forEach(([key,item]) => { if (item != null) value.append(key, String(item)) }); const result = value.toString(); return result ? \`?\${result}\` : '' }\n`

export function generateFetchClient(operations: Operation[]): GeneratedFile {
  const functions = operations
    .map(
      (operation) =>
        `export async function ${operationName(operation)}(params: RequestParams = {}, baseUrl = '', injectedFetch: typeof fetch = fetch) {\n  const response = await injectedFetch(baseUrl + ${pathExpression(operation.path)} + queryString(params.query), { method: '${operation.method}', headers: { 'Content-Type': 'application/json', ...params.headers }, body: params.body === undefined ? undefined : JSON.stringify(params.body), signal: params.signal })\n  const body = response.status === 204 ? undefined : await response.json().catch(() => response.text())\n  if (!response.ok) throw { status: response.status, body } satisfies ApiError\n  return body\n}`,
    )
    .join('\n\n')
  return {
    name: 'api-fetch.ts',
    language: 'typescript',
    content: `/* Generated by API Bridge. Authentication can be injected through headers. */\n${shared}\n${functions}\n`,
    warnings: [],
  }
}

export function generateAxiosClient(operations: Operation[]): GeneratedFile {
  const functions = operations
    .map(
      (operation) =>
        `export async function ${operationName(operation)}(client: AxiosInstance, params: RequestParams = {}) {\n  try { const response = await client.request({ url: ${pathExpression(operation.path)}, method: '${operation.method}', params: params.query, headers: params.headers, data: params.body, signal: params.signal }); return response.data }\n  catch (error) { if (isAxiosError(error)) throw { status: error.response?.status ?? 0, body: error.response?.data } satisfies ApiError; throw error }\n}`,
    )
    .join('\n\n')
  return {
    name: 'api-axios.ts',
    language: 'typescript',
    content: `/* Generated by API Bridge. Configure baseURL and authentication on the injected Axios instance. */\nimport { isAxiosError, type AxiosInstance } from 'axios'\n${shared}\n${functions}\n`,
    warnings: [],
  }
}

export function generateQueryOptions(operations: Operation[]): GeneratedFile {
  const content = operations
    .map((operation) => {
      const name = operationName(operation)
      const mutation = !['GET', 'HEAD'].includes(operation.method)
      return mutation
        ? `export const ${name}MutationOptions = (params: RequestParams = {}) => mutationOptions({ mutationKey: [${JSON.stringify(name)}], mutationFn: () => ${name}(params) })`
        : `export const ${name}QueryOptions = (params: RequestParams = {}) => queryOptions({ queryKey: [${JSON.stringify(name)}, params] as const, queryFn: ({ signal }) => ${name}({ ...params, signal }) })`
    })
    .join('\n\n')
  return {
    name: 'api-query-options.ts',
    language: 'typescript',
    content: `/* Generated TanStack Query v5 option factories; compose them with useQuery/useMutation. */\nimport { mutationOptions, queryOptions } from '@tanstack/react-query'\nimport { ${operations.map(operationName).join(', ')}, type RequestParams } from './api-fetch'\n\n${content}\n`,
    warnings: [],
  }
}

export function generateClients(operations: Operation[]) {
  return [
    generateFetchClient(operations),
    generateAxiosClient(operations),
    generateQueryOptions(operations),
  ]
}
