import type { MockScenario, OpenApiDocument, Operation, ScenarioStep } from './types'

const stableId = (operationId: string, suffix: string) =>
  `${operationId}--${suffix
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')}`

function responseBody(operation: Operation, status: number) {
  const response =
    operation.responses.find((item) => Number(item.status) === status) ??
    operation.responses.find((item) => /^2/.test(item.status)) ??
    operation.responses[0]
  const schema = response?.schema
  const fallback =
    schema?.type === 'array' || schema?.items
      ? []
      : schema?.type === 'string'
        ? ''
        : schema?.type === 'number' || schema?.type === 'integer'
          ? 0
          : schema?.type === 'boolean'
            ? false
            : {}
  return JSON.stringify(response?.example ?? fallback, null, 2)
}

export function createScenario(
  operation: Operation,
  name = 'Default success',
  status?: number,
): MockScenario {
  const selectedStatus =
    status ?? Number(operation.responses.find((item) => /^2\d\d$/.test(item.status))?.status ?? 200)
  return {
    id: stableId(operation.id, name),
    operationId: operation.id,
    name,
    isDefault: name === 'Default success',
    status: selectedStatus,
    headers: { 'Content-Type': 'application/json' },
    bodyType: 'json',
    body: responseBody(operation, selectedStatus),
    delayMs: 0,
    failure: 'none',
    sequence: [],
  }
}

export function createPresetScenarios(operation: Operation) {
  const success = createScenario(operation)
  const empty = { ...createScenario(operation, 'Empty data'), body: '[]' }
  const errors = [401, 403, 404, 409, 422, 429, 500].map((status) => ({
    ...createScenario(operation, `${status} error`, status),
    isDefault: false,
    body: JSON.stringify({ message: `HTTP ${status}` }, null, 2),
  }))
  return [success, empty, ...errors]
}

export function normalizeScenarios(scenarios: MockScenario[], defaultId?: string) {
  const requested =
    defaultId && scenarios.some((item) => item.id === defaultId)
      ? defaultId
      : (scenarios.find((item) => item.isDefault)?.id ?? scenarios[0]?.id)
  return scenarios.map((item) => ({
    ...item,
    delayMs: Math.max(0, Math.min(30_000, item.delayMs)),
    isDefault: item.id === requested,
  }))
}

export function duplicateScenario(scenario: MockScenario, existing: MockScenario[]) {
  let index = 2
  let name = `${scenario.name} copy`
  while (existing.some((item) => item.name === name)) name = `${scenario.name} copy ${index++}`
  return {
    ...scenario,
    id: stableId(scenario.operationId, `${name}-${existing.length}`),
    name,
    isDefault: false,
    headers: { ...scenario.headers },
    sequence: scenario.sequence.map((step) => ({ ...step, headers: { ...step.headers } })),
  }
}

export function moveScenario(scenarios: MockScenario[], from: number, to: number) {
  const next = [...scenarios]
  const [item] = next.splice(from, 1)
  if (item) next.splice(Math.max(0, Math.min(to, next.length)), 0, item)
  return next
}

export function validateScenarioJson(scenario: MockScenario) {
  if (scenario.bodyType !== 'json') return undefined
  try {
    JSON.parse(scenario.body)
    return undefined
  } catch (error) {
    return error instanceof Error ? error.message : String(error)
  }
}

export function sequenceStep(status: number, body: unknown): ScenarioStep {
  return {
    status,
    body: JSON.stringify(body, null, 2),
    headers: { 'Content-Type': 'application/json' },
  }
}

export function generateScenarioMsw(
  document: OpenApiDocument,
  operation: Operation,
  scenarios: MockScenario[],
) {
  void document
  const stable = normalizeScenarios(scenarios)
  const serialized = stable
    .map(
      (scenario) =>
        `  ${JSON.stringify(scenario.id)}: ${JSON.stringify({ status: scenario.status, headers: scenario.headers, bodyType: scenario.bodyType, body: scenario.body, delayMs: scenario.delayMs, failure: scenario.failure, sequence: scenario.sequence })}`,
    )
    .join(',\n')
  const method = operation.method.toLowerCase()
  const path = `*${operation.path.replace(/{([^}]+)}/g, ':$1')}`
  return `/* Generated by API Bridge. Standalone MSW 2.x scenarios. */\nimport { delay, http, HttpResponse } from 'msw'\n\nconst scenarios = {\n${serialized}\n} as const\ntype ScenarioId = keyof typeof scenarios\nlet sequenceIndex = 0\nexport let runtimeScenario: ScenarioId = ${JSON.stringify(stable.find((item) => item.isDefault)?.id ?? stable[0]?.id ?? '')}\nexport const setApiScenario = (id: ScenarioId) => { runtimeScenario = id; sequenceIndex = 0 }\n\nexport const handlers = [\n  http.${method}(${JSON.stringify(path)}, async ({ request }) => {\n    const url = new URL(request.url)\n    const requested = url.searchParams.get('_scenario') ?? request.headers.get('x-api-scenario') ?? (typeof process !== 'undefined' ? process.env.API_SCENARIO : undefined) ?? runtimeScenario\n    const scenario = scenarios[requested as ScenarioId] ?? scenarios[runtimeScenario]\n    if (scenario.delayMs) await delay(scenario.delayMs)\n    if (scenario.failure === 'network-error' || scenario.failure === 'connection-refused') return HttpResponse.error()\n    if (scenario.failure === 'timeout') await delay('infinite')\n    const steps = scenario.sequence as readonly { status: number; body: string; headers: Record<string, string> }[]\n    const selected = steps.length ? steps[Math.min(sequenceIndex++, steps.length - 1)] : scenario\n    const body = scenario.bodyType === 'json' ? JSON.parse(selected.body) : selected.body\n    return scenario.bodyType === 'json' ? HttpResponse.json(body, { status: selected.status, headers: selected.headers }) : new HttpResponse(body, { status: selected.status, headers: selected.headers })\n  }),\n]\n`
}
